name: "Build Main"
on:
  push:
    paths:
      - "src/*"
      - "package-lock.json"
      - "package.json"
      - "action.yml"
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - name: Install Dependencies
        run: npm ci --ignore-scripts
      - name: lint
        run: npm run lint:ci
      - name: format check
        run: npm run format:ci
      - name: run build
        run: npm run build
      - name: run tests
        run: npm run test:ci
      - uses: inception-health/otel-upload-test-artifact-action@v1
        if: always()
        with:
          jobName: "lint-and-test"
          stepName: "run tests"
          path: "junit.xml"
          type: "junit"
          githubToken: ${{ secrets.GITHUB_TOKEN }}
  release-please:
    runs-on: ubuntu-latest
    needs: [lint-and-test]
    steps:
      - id: release
        uses: GoogleCloudPlatform/release-please-action@v2
        with:
          token: "${{ secrets.BUILD_PAT }}"
          release-type: node
          package-name: opentelemetry-exporter-trace-otlp-file
      - if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v2
      - if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - if: ${{ steps.release.outputs.release_created }}
        name: Install Dependencies
        run: npm ci --ignore-scripts
      - if: ${{ steps.release.outputs.release_created }}
        name: Publish
        run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
