name: "Build Main"
on:
  push:
    paths:
      - "src/*"
      - "package-lock.json"
      - "package.json"
      - "action.yml"
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - name: Install Dependencies
        run: npm ci --ignore-scripts
      - name: lint
        run: npm run lint:ci
      - name: format check
        run: npm run format:ci
      - name: run tests
        run: npm run test:ci
  tag:
    runs-on: ubuntu-latest
    needs: [lint, update-dist]
    steps:
      - uses: actions/checkout@v2
      - name: autotag
        uses: butlerlogic/action-autotag@stable
        env:
          GITHUB_TOKEN: "${{ secrets.BUILD_PAT }}"
        with:
          strategy: package
          tag_prefix: "v"
